import { useEffect, useRef, useState } from 'react';
import type { AdProviderKind } from '../../lib/ads';
import { getAdProvider } from '../../lib/ads';
import { AdsenseAd } from './AdsenseAdProvider';
import { PlaceholderAd } from './PlaceholderAdProvider';

/**
 * Timing constants for the bottom-panel rotation.
 *
 * State A (ad): the resolved ad provider renders for
 * `AD_DISPLAY_DURATION_MS`, then the panel switches to
 *
 * State B (filler): the provider disclosure text renders for
 * `AD_GAP_DURATION_MS`, then the panel returns to State A.
 *
 * Both values live here (not in lib/ads.ts) because they are purely a
 * presentation concern of this panel; adjust them freely without
 * touching provider logic.
 */
export const AD_DISPLAY_DURATION_MS = 25_000; // ~20–30s: ad visible
export const AD_GAP_DURATION_MS = 12_000; // ~10–15s: disclosure filler visible

/**
 * Shared surface of the composer + bottom panel: the border/background
 * colors both halves are built from. The composer (MessageInput) imports
 * this constant and adds its top-half geometry (rounded top corners, no
 * bottom border); this panel adds the bottom half (square top corners,
 * rounded bottom corners). One owner of the colors — the two halves
 * cannot drift apart.
 */
export const PANEL_SURFACE =
  'border bg-white border-zinc-200 dark:border-zinc-800 dark:bg-zinc-900';

/** Panel height floor shared by both rotation states: no jump on flip. */
const PANEL_MIN_H = 'min-h-[60px]';

/**
 * Content crossfade for the state swap. Subtle by design: the panel
 * box itself never moves or resizes, only the content inside fades in
 * over the stable container (see `.animate-fade` in index.css — pure
 * opacity, 250ms, disabled under prefers-reduced-motion).
 */
const FADE_IN = 'animate-fade';

/**
 * The disclosure "filler" shown while no ad is on screen. The wording
 * is identical to the old composer footer; the a/an grammar follows
 * the provider label exactly as it did there.
 *
 * While the provider label is still loading (models list not fetched
 * yet) a neutral hint is shown instead — the panel never renders as a
 * confusing blank block, and no invented provider name is displayed.
 */
function DisclosureFiller({ providerName }: { providerName?: string }) {
  return (
    <div
      data-ad-filler="disclosure"
      className={[
        'flex w-full items-center justify-center px-4 text-center',
        PANEL_MIN_H,
        'select-none',
        FADE_IN,
      ].join(' ')}
    >
      <p className="text-[11px] text-zinc-500 dark:text-zinc-400">
        {providerName
          ? /^[aeiou]/i.test(providerName)
            ? `Responses are generated by an ${providerName} provider.`
            : `Responses are generated by a ${providerName} provider.`
          : 'Responses are generated by AI models.'}
      </p>
    </div>
  );
}

interface BottomAdPanelProps {
  /**
   * Short, user-facing label of which provider is currently serving
   * the selected model (e.g. "demo", "AI gateway"). Drives the
   * disclosure filler; while it is undefined a neutral loading hint
   * is shown instead.
   */
  providerName?: string;
  className?: string;
}

/**
 * The product's single bottom ad placement, directly attached to the
 * composer (ChatWindow → BottomAdPanel → PlaceholderAd / AdsenseAd).
 *
 * Rotation: the panel alternates between the ad (State A) and the
 * disclosure filler (State B) on the timers above. The rotation logic
 * lives here — at the panel level — so any provider (placeholder
 * today, AdSense in Phase 3) gets the same behaviour without
 * per-provider changes.
 *
 * Layout: the panel is the bottom half of one attached surface with
 * the composer (see the exported PANEL_SURFACE both halves build on);
 * height is pinned by PANEL_MIN_H
 * in both rotation states so nothing jumps when the state flips.
 *
 * Timing robustness: see useRotation — background-tab timer
 * throttling cannot compress cycles or burst phase flips.
 *
 * AdSense policy note: the filler state means the <ins> is unmounted
 * for stretches of time. Remounting re-requests the slot, which is
 * permitted, but automatic timed refresh policies should be
 * re-checked against AdSense rules before production traffic —
 * flagged here rather than guessed. (Local structural path verified
 * only; real network delivery has never been exercised in this repo.)
 */
export function BottomAdPanel({ providerName, className }: BottomAdPanelProps) {
  const kind = getAdProvider();
  const showAd = useRotation(kind);

  // Ad-free build: just the disclosure, no rotation.
  if (kind === 'none') {
    return (
      <div className={[PANEL_SURFACE, 'w-full rounded-b-2xl', className ?? ''].join(' ')}>
        <div aria-live="polite">
          <DisclosureFiller providerName={providerName} />
        </div>
      </div>
    );
  }

  return (
    <div className={['w-full rounded-b-2xl', PANEL_SURFACE, className ?? ''].join(' ')}>
      {showAd ? (
        <div className={FADE_IN}>
          {kind === 'adsense' ? (
            <AdsenseAd variant="bottom" className="w-full" />
          ) : (
            <PlaceholderAd variant="bottom" className="w-full" />
          )}
        </div>
      ) : null}
      {/* Live region owns the disclosure only — ad content is never
        announced. The wrapper stays mounted (empty) during the ad phase:
        a live region only fires for changes inside an existing region, so
        mounting the filler with aria-live would announce nothing. */}
      <div aria-live="polite">
        {!showAd && <DisclosureFiller providerName={providerName} />}
      </div>
    </div>
  );
}

/**
 * Rotation state machine for the panel: returns whether the ad (true)
 * or the disclosure filler (false) should currently render.
 *
 * Robustness against background-tab throttling:
 *  - One `setTimeout` is armed per phase (not a tick interval); each
 *    flip re-arms exactly once. Throttled/coalesced timers can
 *    therefore never produce burst flips or compressed cycles.
 *  - The current phase is tracked in a ref; on `visibilitychange` the
 *    pending timeout is torn down when the tab hides and re-armed with
 *    the exact remaining wall-clock time when it returns, so a hidden
 *    tab neither accumulates stale flips nor loses phase position.
 */
function useRotation(kind: AdProviderKind): boolean {
  const [showAd, setShowAd] = useState(true);
  const showAdRef = useRef(true); // phase truth; state mirrors it
  const timerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  useEffect(() => {
    if (kind === 'none') return undefined; // ad-free build: static filler

    const phaseDuration = () => (showAdRef.current ? AD_DISPLAY_DURATION_MS : AD_GAP_DURATION_MS);

    const arm = (delay: number) => {
      clearTimeout(timerRef.current);
      timerRef.current = setTimeout(flip, delay);
    };

    function flip() {
      const next = !showAdRef.current;
      showAdRef.current = next;
      setShowAd(next);
      arm(next ? AD_GAP_DURATION_MS : AD_DISPLAY_DURATION_MS);
    }

    const onVisibility = () => {
      if (document.hidden) {
        clearTimeout(timerRef.current);
        timerRef.current = undefined;
      } else {
        // Re-arm the full phase: hidden tabs are paused, and a full
        // restart of the visible phase is the least surprising and
        // cannot produce negative elapsed math.
        arm(phaseDuration());
      }
    };

    if (!document.hidden) arm(phaseDuration());
    document.addEventListener('visibilitychange', onVisibility);
    return () => {
      document.removeEventListener('visibilitychange', onVisibility);
      clearTimeout(timerRef.current);
      timerRef.current = undefined;
    };
    // `showAd` state changes are mirrored through showAdRef, not by
    // re-running this effect (which would restart the phase timer).
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [kind]);

  return showAd;
}
