import { useEffect, useRef, useState, type FormEvent, type KeyboardEvent } from 'react';
import { classNames } from '../../lib/format';

interface Props {
  onSend: (text: string) => void;
  onStop: () => void;
  isStreaming: boolean;
  disabled?: boolean;
  placeholder?: string;
}

export function MessageInput({
  onSend,
  onStop,
  isStreaming,
  disabled,
  placeholder,
}: Props) {
  const [text, setText] = useState('');
  const taRef = useRef<HTMLTextAreaElement | null>(null);

  // Auto-grow up to ~6 lines.
  useEffect(() => {
    const ta = taRef.current;
    if (!ta) return;
    ta.style.height = 'auto';
    ta.style.height = Math.min(ta.scrollHeight, 180) + 'px';
  }, [text]);

  const submit = () => {
    const v = text.trim();
    if (!v || isStreaming) return;
    onSend(v);
    setText('');
  };

  const onKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      submit();
    }
  };

  return (
    <form
      onSubmit={(e: FormEvent) => {
        e.preventDefault();
        submit();
      }}
      className="mx-auto w-full max-w-3xl px-3 pb-3 sm:px-6 sm:pb-4"
    >
      <div
        className={classNames(
          'flex items-end gap-2 rounded-2xl border bg-white p-2 shadow-sm',
          'border-zinc-300 focus-within:border-brand-500 focus-within:ring-1 focus-within:ring-brand-500',
          'dark:border-zinc-700 dark:bg-zinc-900',
        )}
      >
        <textarea
          ref={taRef}
          value={text}
          rows={1}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={onKeyDown}
          disabled={disabled}
          placeholder={
            placeholder ?? 'Message Web AI…   (Enter to send, Shift+Enter for newline)'
          }
          className={classNames(
            'max-h-[180px] min-h-[40px] flex-1 resize-none bg-transparent px-2 py-2 text-sm',
            'text-zinc-900 placeholder:text-zinc-400 focus:outline-none',
            'dark:text-zinc-100',
          )}
        />
        {isStreaming ? (
          <button
            type="button"
            onClick={onStop}
            className="inline-flex h-9 shrink-0 items-center gap-1 rounded-lg bg-zinc-900 px-3 text-sm font-medium text-white hover:bg-zinc-800 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-200"
          >
            <span className="inline-block h-2 w-2 rounded-sm bg-current" />
            Stop
          </button>
        ) : (
          <button
            type="submit"
            disabled={!text.trim() || disabled}
            className={classNames(
              'inline-flex h-9 shrink-0 items-center gap-1 rounded-lg px-3 text-sm font-medium',
              'bg-brand-500 text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50',
            )}
          >
            Send
            <span aria-hidden>➤</span>
          </button>
        )}
      </div>
      <p className="mt-1 text-center text-[11px] text-zinc-500 dark:text-zinc-500">
        Responses are generated by a mock provider in Phase 1.
      </p>
    </form>
  );
}
